# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "nokogiri", "~> 1.15"

gem "httparty", "~> 0.21.0"

gem "awesome_print", "~> 1.9"

gem "sqlite3", "~> 1.6"

gem "pg", "~> 1.5"
